### ISSUE TITLE
Sample not working! :(

### ISSUE THREAD

**Issue by rodrix385** [vench/php-lsa#3]
I am running the sample code:
$documents = [
            "The quick brown fox jumped over the lazy dog",
            "hey diddle diddle, the cat and the fiddle",
            "the cow jumped over the moon",
            "the little dog laughed to see such fun",
            "and the dish ran away with the spoon",
     ];

     $lsa = new LSA(4);
     $trans = $lsa->fitTransform($documents);
     
     $query = "the brown fox ran around the dog";
     $index = $lsa->query($query, $trans);
     echo $documents[$index], PHP_EOL;

...and I get
| <b>Fatal error</b>:  Uncaught Exception: Error matrix dimension in E:\Dropbox\XAMPP7\htdocs\text-analysis\src\lib.php:19
  | Stack trace:
  | #0 E:\Dropbox\XAMPP7\htdocs\text-analysis\src\LSA.php(117): PHPLsa\mult(Array, Array)
  | #1 E:\Dropbox\XAMPP7\htdocs\text-analysis\src\LSA.php(185): PHPLsa\LSA-&gt;transform(Array)
  | #2 E:\Dropbox\XAMPP7\htdocs\text-analysis\test.php(29): PHPLsa\LSA-&gt;query('the brown fox r...', Array)
  | #3 {main}
  | thrown in <b>E:\Dropbox\XAMPP7\htdocs\text-analysis\src\lib.php</b> on line <b>19</b><br />
  |  

Using PHP 7.09 under Windows on XAMPP

**Comment by rodrix385** [comment]
I found your library on phpclasses.com, but I can't make it work :/
